### ISSUE TITLE
Automated builds?

### ISSUE THREAD

**Issue by Manouchehri** [microsoft/codeql-container#21]
It seems that `mcr.microsoft.com/cstsectools/codeql-container` hasn't been updated since November 3rd, 2020 (CodeQL 2.3.2).

Would it be possible to have continuous builds of the `codeql-container` image? It looks like maybe that was the purpose of #1, but I'm not sure.

**Comment by InbarRose** [comment]
If not automated, at least can a new official image be produced from latest code?

**Comment by jacobmsft** [comment]
working on it now, hit an issue with Ruby, if that doesnt get resolved, I'll avoid compiling ruby for now:https://github.com/github/codeql/issues/7193

**Comment by Manouchehri** [comment]
@jacobmsft I believe https://github.com/microsoft/codeql-container/pull/34 should resolve that issue.

**Comment by jacobmsft** [comment]
I tried that locally, didnt work for me:

/usr/local/codeql-home# codeql query compile --search-path=/usr/local/codeql-home/codeql-repo/ruby/ql/ --threads=0 ${CODEQL_HOME}/codeql-repo/ruby/ql/src/codeql-suites/*.qls
ERROR: Referenced pack 'codeql/suite-helpers' not found. (/usr/local/codeql-home/codeql-repo/ruby/ql/src/qlpack.yml:1,1-1)
A fatal error occurred: Could not resolve library path for /usr/local/codeql-home/codeql-repo/ruby/ql/src

**Comment by jacobmsft** [comment]
New image pushed and automated builds setup for every 2 weeks. I'll close this issue, open a new issue if problem persists.
